# Configurações de build
[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

# Configurações de redirecionamento para React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy para API (alternativa para resolver CORS)
[[redirects]]
  from = "/api/*"
  to = "https://movie-project-api-tom2.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
