services:
  # Serviço para o backend
  - type: web
    name: movie-project-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://vascoc:vascoc@cluster0.wkllmaa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: FRONTEND_URL
        fromService:
          name: movie-project-frontend
          type: web
          property: url

  # Serviço para o frontend
  - type: web
    name: movie-project-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
